DROP TABLE IF EXISTS bug;
DROP TYPE bugPriority;
DROP TYPE bugStatus;
DROP TABLE IF EXISTS teamMember;
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS organisationTransfer;
DROP TABLE IF EXISTS organisation;
DROP TABLE IF EXISTS profile;