// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (Organisation, error)
	CreateOrganisationTransfer(ctx context.Context, arg CreateOrganisationTransferParams) (Organisationtransfer, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	GetActiveOrganisationTransfer(ctx context.Context, organisation uuid.UUID) (Organisationtransfer, error)
	GetOrganisation(ctx context.Context, owner uuid.UUID) (Organisation, error)
	GetProfile(ctx context.Context, id uuid.UUID) (Profile, error)
	GetProfileByEmail(ctx context.Context, email string) (Profile, error)
	UpdateOrganisation(ctx context.Context, arg UpdateOrganisationParams) (Organisation, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (Profile, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UpdateTokenId(ctx context.Context, arg UpdateTokenIdParams) (Profile, error)
	UpdateTokenIdByEmail(ctx context.Context, arg UpdateTokenIdByEmailParams) (Profile, error)
	VerifyProfile(ctx context.Context, id uuid.UUID) (Profile, error)
}

var _ Querier = (*Queries)(nil)
