// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: teamMember.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTeamMember = `-- name: CreateTeamMember :one
INSERT INTO teamMember (team, profile, admin)
VALUES ($1, $2, $3)
RETURNING team, profile, admin, createdat, updatedat
`

type CreateTeamMemberParams struct {
	Team    uuid.UUID `json:"team"`
	Profile uuid.UUID `json:"profile"`
	Admin   bool      `json:"admin"`
}

func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (Teammember, error) {
	row := q.db.QueryRow(ctx, createTeamMember, arg.Team, arg.Profile, arg.Admin)
	var i Teammember
	err := row.Scan(
		&i.Team,
		&i.Profile,
		&i.Admin,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
